# Generated by Django 4.2.12 on 2024-07-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_todo_data_tododata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='details',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tododata',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
