# Generated by Django 4.2.12 on 2024-07-17 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_alter_tododata_date_alter_tododata_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 17, 6, 19, 35, 234564, tzinfo=datetime.timezone.utc)),
        ),
    ]
