# Generated by Django 4.2.12 on 2024-07-17 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_alter_tododata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
