# Generated by Django 4.2.12 on 2024-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_todo_todo_data_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_data',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
