# Generated by Django 4.2.12 on 2024-07-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0003_todo_data_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo_data',
            options={'ordering': ['done', 'date']},
        ),
        migrations.AddField(
            model_name='todo_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
