# Generated by Django 4.2.12 on 2024-07-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0005_remove_todo_data_user_todo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Todo_List',
        ),
    ]
